#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Enter a valid number"
    exit 1
fi

number=$1
sum=0

while [ "$number" -gt 0 ]; 
do
    digit=$((number % 10))
    sum=$((sum + digit))
    number=$((number / 10))
done

echo "Original Number: $1"
echo "Sum of Digits: $sum"

